---
- include: setup.yml
  become: true
  tags:
    - ckb_benchmark_install

- include: install.yml
  become: true
  tags:
    - ckb_benchmark_install

- include: miner.yml
  become: true
  tags:
    - ckb_benchmark_prepare

- include: prepare.yml
  tags:
    - ckb_benchmark_prepare

- include: miner.yml
  become: true
  tags:
    - ckb_benchmark_start

- include: bench.yml
  tags:
    - ckb_benchmark_start

- include: miner.yml
  become: true
  tags:
    - ckb_benchmark_miner_start


- include: bench_with_tps.yml
  tags:
    - ckb_benchmark_with_tps

- include: stop.yml
  tags:
    - ckb_bench_stop

- include: clean.yml
  tags:
    - ckb_bench_clean