---
- include: setup.yml
  become: true
  tags:
    - ckb_benchmark_install

- include: install.yml
  become: true
  tags:
    - ckb_benchmark_install

- include: miner.yml
  become: true
  tags:
    - ckb_benchmark_prepare

- include: prepare.yml
  tags:
    - ckb_benchmark_prepare

- include: miner.yml
  become: true
  tags:
    - ckb_benchmark_start

- include: bench.yml
  tags:
    - ckb_benchmark_start
