---
- include: setup.yml
  become: true
  tags:
    - ckb_benchmark_setup
    - ckb_benchmark_install
    - ckb_benchmark_configure

- include: install.yml
  become: true
  tags:
    - ckb_benchmark_install

- include: configure.yml
  become: true
  tags:
    - ckb_benchmark_configure

- name: Start CKB Benchmark
  shell:
    cmd: |
      timeout 40m {{ ckb_benchmark_workspace }}/tps-bench bench \
          --spec {{ ckb_benchmark_workspace }}/tps-bench.toml \
          --rpc-urls {{ ckb_benchmark_rpc_urls | join(' ') }}
  tags:
    - ckb_benchmark_start
  when: ckb_benchmark_skip_best_tps_caculation is not defined or ckb_benchmark_skip_best_tps_caculation == false

- name: Start CKB Benchmark
  shell:
    cmd: |
      timeout 40m {{ ckb_benchmark_workspace }}/tps-bench bench \
          --spec {{ ckb_benchmark_workspace }}/tps-bench.toml \
          --rpc-urls {{ ckb_benchmark_rpc_urls | join(' ') }} \
          --skip-best-tps-caculation
  tags:
    - ckb_benchmark_start
  when: ckb_benchmark_skip_best_tps_caculation is defined and ckb_benchmark_skip_best_tps_caculation == true
