---
- name: Pre-mine Blocks {{ ckb_benchmark_premine_blocks }}
  environment:
    RUST_LOG: "info,ckb-bench=debug"
  shell:
    cmd: |
      {{ ckb_benchmark_workspace }}/ckb-bench miner \
          --rpc-urls {{ ckb_benchmark_rpc_urls[0] }} \
          --n-blocks {{ ckb_benchmark_premine_blocks }} \
          --mining-interval-ms 0 \
      | tee --append {{ ckb_benchmark_logfile }}

- name: Pre-generate Cells To Users
  environment:
    RUST_LOG: "info,ckb-bench=debug"
    CKB_BENCH_OWNER_PRIVKEY: "{{ ckb_benchmark_owner_privkey }}"
  shell:
    cmd: |
      {{ ckb_benchmark_workspace }}/ckb-bench dispatch \
          --rpc-urls          {{ ckb_benchmark_rpc_urls | join(',') }} \
          --data-dir          {{ ckb_benchmark_data_dir }} \
          --n-users           {{ ckb_benchmark_n_users }} \
          --cells-per-user    {{ ckb_benchmark_cells_per_user }} \
          --capacity-per-cell {{ ckb_benchmark_capacity_per_cell }} \
      | tee --append {{ ckb_benchmark_logfile }}
